name: SkyPvPBeta
version: 1.0
author: EnderReturn, Vyrrex
main: skypvp.Main.Main
commands:
  skypvp:
  spawn:
  kits:
  build:
  fly:
  vanish:
  cc:
  ec:
  wb:
  stats:
  invsee:
  votekick:
  ja:
  nein:
  uja:
  unein:
  umfrage:
  reset:
  feed:
  heal:
  